name = "Vierzig"
license = "Creative Commons Attribution 3.0"
licenselink = "https://github.com/ASVBPREAUBV/vierzig/blob/master/LICENSE.md"
description = "A product website for creators."
homepage = "https://vierzig-theme-demo.netlify.com/"
tags = ["portfolio", "company", "contact form", "google analytics", "blog", "cms", "netlify"]
features = ["blog, NetlifyCMS"]
min_version = "0.29"


[author]
  name = "Paul Mayer"
  homepage = "https://github.com/ASVBPREAUBV"

[original]
  name = "Marcus Virginia"
  homepage = "https://marcusv.me"

[original]
  author = "AJ"
  name = "HTML5 Up"
  homepage = "https://html5up.net/forty"